### ISSUE TITLE
Smart-Contract TODOs (for paper)

### ISSUE THREAD

**Issue by Ehsan-Home** [AKEB-asyemmtric-key-each-bidder/AKEB-SmartContract#4]
## TODOs

- [x] Breakdown gas price
- [ ] Convert encoded bid string into uint256 to reduce gas costs
- [x] Test the system in private network for a period of time
- [x] Auctioneer should start and finish the auction
